// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8QKk009CA7Qrgm7TP6Y1f3z8jSyCHA4Q',
    appId: '1:1069516027479:web:8b3007acac564ff36b9512',
    messagingSenderId: '1069516027479',
    projectId: 'luxora-8cee1',
    authDomain: 'luxora-8cee1.firebaseapp.com',
    storageBucket: 'luxora-8cee1.firebasestorage.app',
    measurementId: 'G-TKEEP5DF2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRshCRzRLYQcJxsKST2LhtjOFU9HsUJt8',
    appId: '1:1069516027479:android:f1f4a22cbd6dba126b9512',
    messagingSenderId: '1069516027479',
    projectId: 'luxora-8cee1',
    storageBucket: 'luxora-8cee1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGCdxj2di8sfgqFKSHnCYS0ni0HcvJ300',
    appId: '1:1069516027479:ios:66263649d91ab8586b9512',
    messagingSenderId: '1069516027479',
    projectId: 'luxora-8cee1',
    storageBucket: 'luxora-8cee1.firebasestorage.app',
    iosBundleId: 'com.example.luxora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGCdxj2di8sfgqFKSHnCYS0ni0HcvJ300',
    appId: '1:1069516027479:ios:66263649d91ab8586b9512',
    messagingSenderId: '1069516027479',
    projectId: 'luxora-8cee1',
    storageBucket: 'luxora-8cee1.firebasestorage.app',
    iosBundleId: 'com.example.luxora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8QKk009CA7Qrgm7TP6Y1f3z8jSyCHA4Q',
    appId: '1:1069516027479:web:2a0e3bacb2e9167e6b9512',
    messagingSenderId: '1069516027479',
    projectId: 'luxora-8cee1',
    authDomain: 'luxora-8cee1.firebaseapp.com',
    storageBucket: 'luxora-8cee1.firebasestorage.app',
    measurementId: 'G-XKSF2X1TVG',
  );
}
